# frozen_string_literal: true

source 'https://rubygems.org'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 8.0.2'
# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 6.6'

gem 'jsonrpc-middleware', path: '../../', require: 'jsonrpc' # Remove 'path' in your code

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
end
