module JSONRPC
  class Notification
    attr_reader jsonrpc: String
    attr_reader method: String
    attr_reader params: params_type

    def initialize: (method: String, ?params: params_type) -> void
    def to_h: -> symbol_hash
    def to_json: (*untyped) -> String
    def ==: (untyped) -> bool
    alias eql? ==
    def hash: -> Integer

    private
    def validate_method: (String) -> void
    def validate_params: (params_type) -> void
  end
end
