module JSONRPC
  class Parser
    def parse: (String json) -> (Request | Notification | BatchRequest | Error)

    private

    def parse_single: (interned_hash data) -> (Request | Notification | Error)
    def parse_batch: (Array[interned_hash] data) -> BatchRequest
    def parse_single_for_batch: (interned_hash data) -> (Request | Notification)
    def validate_jsonrpc_version: (interned_hash data) -> void
    def validate_request_structure: (interned_hash data) -> void
  end
end
