module JSONRPC
  # Common types used across the library
  type params_type = Hash[untyped, untyped] | Array[untyped] | nil
  type id_type = String | Integer | nil
  type data_type = Hash[untyped, untyped] | Array[untyped] | String | Numeric | bool | nil

  VERSION: String

  def self.configure: () { (Configuration) -> void } -> void
  def self.configuration: -> Configuration
end
